project_id = "pukcbqfjzswqmjkhwzfk"

[functions.processar-ficha]
verify_jwt = false

[functions.transcrever-audio]
verify_jwt = false

[functions.notificar-ficha-whatsapp]
verify_jwt = false

[functions.popular-tags-clientes]
verify_jwt = false

[functions.sugerir-tags-texto]
verify_jwt = false
